---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{GITHUB_REPO}}
  namespace: system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{GITHUB_REPO}}
    spec:
      serviceAccount: {{GITHUB_REPO}}
      containers:
        - name: {{GITHUB_REPO}}
          image: {{CONTAINER}}:{{VERSION}}
          command:
            - "./{{GITHUB_REPO}}"
          args:
            - "controller"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: system
  name: {{GITHUB_REPO}}
