#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
REPO="~/.golang-template-repo"

update-repo() {
	pushd "${REPO}"
	git pull
	popd
}

if [ -d "${REPO}" ]; then
	update-depo
else
	git clone https://github.com/mad01/golang-template-repo.git ~/.golang-template-repo
	pushd "${REPO}"
	bash -c ./gen
	popd
fi
